algoritmo "ex01"
// A imobiliária Imóbilis vende apenas terrenos retangulares.
//Faça um algoritmo para ler as
//dimensões de um terreno e depois exibir a área do terreno.
//
var
larg,alt,area:real
inicio
// Seção de Comandos
escreval ("Digite a largura do terreno em metros:")
leia(larg)
escreval ("Digite a altura do terreno em metros:")
leia (alt)

area <- larg * alt

escreval("A area do seu terreno em metros quadrados é:", area)
fimalgoritmo
