algoritmo "ex02"
//Faça um algoritmo para calcular quantas ferraduras são necessárias
// para equipar todos os cavalos comprados para um haras.
var
qtde_cavalos,total_ferr:inteiro
inicio
// Seção de Comandos
escreval ("Digite a quantidade de cavalos:")
leia(qtde_cavalos)
total_ferr <- qtde_cavalos * 4
escreval ("O total de ferraduras necessárias é de:")
escreval (total_ferr)

fimalgoritmo
