algoritmo "ex17"
// Alguns países medem temperaturas em graus Celsius, e outros em graus Fahrenheit. Faça
//um algoritmo para ler uma temperatura Celsius e imprimi-la em Fahrenheit (pesquise como
//fazer este tipo de conversão).


var
celsius,fahr:real
inicio
// Seção de Comandos
escreval ("Digite a temperatura em graus Celsius")
leia(celsius)
fahr <- 9/5 * celsius + 32

escreval ("A temperatura em graus Fahrenheit é: ",fahr)


fimalgoritmo
