algoritmo "ex26"
// Faça um algoritmo que receba três números, calcule e mostre a multiplicação desses
//números.
var
num1,num2,num3:inteiro
mult:real
inicio
// Seção de Comandos
escreval ("Digite um número:")
leia (num1)
escreval ("Digite um número:")
leia (num2)
escreval ("Digite um número:")
leia (num3)
mult <- num1 * num2 * num3
escreval ("A multiplicação desses números é:",mult)
fimalgoritmo
