algoritmo "ex27"
// Faça um algoritmo que receba dois números, calcule e mostre a divisão do primeiro número
//pelo segundo. Sabe-se que o segundo número não pode ser zero, portanto não é necessário
//se preocupar com validações
var
num1,num2:inteiro
divi:real
inicio
// Seção de Comandos
escreval ("Digite um número:")
leia (num1)
escreval ("Digite um número:")
leia (num2)
divi<- num1/num2
escreval ("A divisão do numero",num1," com",num2," é:",divi)
fimalgoritmo
